version: "3.9"

services:
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server-backend
    links:
      - mysql-server:mysql
      - zabbix-server-backend:zabbix-server
    restart: unless-stopped
    ports:
      - 10050:10050
    networks:
      - zbx-network

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: J626CzObYr5o
      MYSQL_ROOT_PASSWORD: tpS2k0CE9u9P
      PHP_TZ: America/Sao_Paulo
      ZBX_SERVER_HOST: zabbix-server-backend
      ZBX_SERVER_PORT: 10051
    ports:
      - 80:8080
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-server-backend
    networks:
      - zbx-network

  zabbix-server-backend:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server-backend
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: J626CzObYr5o
      MYSQL_ROOT_PASSWORD: tpS2k0CE9u9P
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    ports:
      - 10051:10051
    restart: unless-stopped
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    networks:
      - zbx-network

  mysql-server:
    image: mysql
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: tpS2k0CE9u9P
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: J626CzObYr5o
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - 3306:3306
    networks:
      - zbx-network
    volumes:
      - ./data/mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1024M

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway
    container_name: zabbix-java-gateway
    restart: unless-stopped
    networks:
      - zbx-network

networks:
  zbx-network:
    driver: bridge
