services:
  zabbix-database:
    image: postgres:15
    container_name: zabbix-database
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - zabbix

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:latest
    container_name: zabbix-snmptraps
    environment:
      ZBX_ENABLE_SNMP_TRAPS: "true"
    volumes:
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps
    ports:
      - "162:162/udp"
    depends_on:
      - zabbix-database
    restart: unless-stopped
    networks:
      - zabbix

  zabbix-server:
    build:
      context: ./Dockerfiles/zabbix-server
      dockerfile: Dockerfile
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    volumes:
      - zabbix-server:/var/lib/zabbix
      - zabbix-server:/var/lib/zabbix/export
      - zabbix-server:/var/lib/zabbix/snmptraps
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-database
    restart: unless-stopped
    networks:
      - zabbix

  zabbix-web:
    build:
      context: ./Dockerfiles/zabbix-web
      dockerfile: Dockerfile
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: zabbix-database
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "America/Sao_Paulo"
    volumes:
      - zabbix-web:/var/lib/zabbix-web
    depends_on:
      - zabbix-server
    networks:
      - zabbix
    ports:
      - "80:8080"
    restart: unless-stopped

  zabbix-agent:
    build:
      context: ./Dockerfiles/zabbix-agent
      dockerfile: Dockerfile
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "zabbix-agent"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "10050:10050"
    volumes:
      - zabbix-agent:/var/lib/zabbix
    depends_on:
      - zabbix-server
    restart: unless-stopped
    networks:
      - zabbix

networks:
  zabbix:

volumes:
  zabbix-database:
  zabbix-snmptraps:
  zabbix-server:
  zabbix-agent:
  zabbix-web:
