version: '3.9'

services:
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server
    links:
    - mysql-server:mysql
    - zabbix-server-mysql:zabbix-server
    restart: unless-stopped
    networks:
    - zbx-network

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-web-nginx-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
      PHP_TZ: America/Sao_Paulo
      ZBX_SERVER_HOST: zabbix-server-mysql
    ports:
    - "80:8080"
    restart: unless-stopped
    depends_on:
    - mysql-server
    - zabbix-server-mysql
    networks:
    - zbx-network

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server-mysql
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    ports:
    - 10051:10051
    restart: unless-stopped
    depends_on:
    - mysql-server
    - zabbix-java-gateway
    networks:
    - zbx-network

  mysql-server:
    image: mysql
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: zabbix
    command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "3306:3306"
    networks:
    - zbx-network
    volumes:
    - ./data/mysql:/var/lib/mysql
    # - ./mysql.config:/etc/mysql/conf.d/mysql.cnf
    deploy:
      resources:
        limits:
          memory: 1024M

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway
    container_name: zabbix-java-gateway
    restart: unless-stopped
    networks:
    - zbx-network

networks:
  zbx-network:
    driver: bridge
