services:
  mysql:
    image: mysql:8
    container_name: zabbix-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/zabbix/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    networks:
      - zabbix
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  snmptraps:
    image: zabbix/zabbix-snmptraps
    container_name: zabbix-snmptraps
    restart: always
    ports:
      - "162:1162/udp"
    volumes:
      - ./data/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
      - ./data/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      - zabbix

  server:
    build:
      context: ./Dockerfiles/zabbix-server
    container_name: zabbix-server
    restart: always
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: "3306"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"
    networks:
      - zabbix
    volumes:
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps:rw
      - zabbix-mibs-data:/usr/share/snmp/mibs:ro

  web:
    build:
      context: ./Dockerfiles/zabbix-web
    container_name: zabbix-web
    restart: always
    ports:
      - "80:8080"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-mysql
      DB_SERVER_PORT: "3306"
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      PHP_TZ: America/Sao_Paulo
    networks:
      - zabbix

  agent:
    build: 
      context: ./Dockerfiles/zabbix-agent
    container_name: zabbix-agent
    restart: always
    privileged: true
    ports:
      - "10050:10050"
    networks:
      - zabbix
    depends_on:
      - server

networks:
  zabbix:
    external: true

volumes:
  zabbix-snmptraps-data:
  zabbix-mibs-data:
